version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: auth_mvp_mongo
    environment:
      - MONGO_INITDB_DATABASE=auth_mvp
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
